project:
  name: quickstart-tableau-server
  owner: quickstart-eng@amazon.com
  package_lambda: true
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  cluster-centos:
    parameters:
      AMIOS: CentOS-7-HVM
      AWSHostedZoneID: ''
      AWSPublicFQDN: ''
      AcceptEULA: 'yes'
      AvailabilityZones: $[alfred_getaz_3]
      ExistingSecurityGroup: ''
      IPAddress: ''
      InstanceType: m4.4xlarge
      KeyPairName: $[alfred_getkeypair]
      Password: $[alfred_genpass_32]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RegCity: Test City
      RegCompany: Test Company
      RegCountry: Test Country
      RegDepartment: Test Department
      RegEmail: testemail@example.com
      RegFirstName: Test First Name
      RegIndustry: Test Industry
      RegLastName: Test Last Name
      RegPhone: Test Phone
      RegState: Test State
      RegTitle: Test Title
      RegZip: Test Zip
      SSLCertificateARN: ''
      SourceCIDR: 10.0.0.0/16
      TableauServerAdminPassword: $[alfred_genpass_32]
      TableauServerAdminUser: admin
      TableauServerLicenseKey: overridden
      Username: qsadmin
      WorkerCount: '2'
    regions:
    - us-west-2
    s3_bucket: ''
    template: templates/tableau-cluster-linux-master.template